#!/bin/sh

if ! command -v nvim 1>/dev/null 2>&1; then
  echo "Error: neovim not installed" >&2
  exit 1
fi

export NVIM_APPNAME="peter.nvim"

# Run Neovim in headless mode:
# 1. Install plugins
# 2. Install Mason packages
# 3. Install treesitter parsers

nvim --headless \
  '+Lazy! restore' \
  '+Lazy! load mason-tool-installer.nvim' \
  '+Lazy! load nvim-treesitter' \
  +qa
